version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chains
      POSTGRES_PASSWORD: chains
      POSTGRES_DB: chains_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    # Используем команду из Dockerfile (python -m bot.main)
    #command: python -m bot.main
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: 